### ISSUE TITLE
Compatibility Issue w/ Scheduler v4.4.0 & Resque v1.26.0

### ISSUE THREAD

**Issue by thetizzo** [resque/resque-scheduler#684]
I'm attempting to upgrade resque and resque-scheduler in an old Rails app and ran into compatibility issue between resque-scheduler 4.4.0 & resque 1.26.0.

When I attempt to start the scheduler with these 2 version together I get the following error output:
```
$ rake resque:scheduler
resque-scheduler: [INFO] 2019-10-18T16:11:30-06:00: Starting
rake aborted!
NoMethodError: undefined method `data_store' for Resque:Module

Tasks: TOP => resque:scheduler
(See full trace by running task with --trace)
```
The gemspec for resque-scheduler 4.4.0 claims compatibility with 1.26 so I figured this was a bug.
```
spec.add_runtime_dependency 'resque', '>= 1.26'
```
This works with resque >= 1.27.0.

It appears that the gemspec has been updated to `resque >= 1.27` on `master` already so not sure if there is anything to do here other than file this issue for posterity but I'm happy to contribute a PR if need be.

**Comment by jeremy** [comment]
#670
